name: codon-optimize
description: A Github action to codon optimize a list of Genbank files.
inputs:
    input:
        description: 'A fasta file with all the sequences that will be read'
        required: true
    output:
        description: 'Path and file name where an output fasta file will be written'
        required: true
    codonTable:
        description: 'A Codon Table in a JSON file format'
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.input-file        }}
        - ${{ inputs.output-file       }}
        - ${{ inputs.input-codon-table }}

author: Friendzymes Team
branding:
    icon:  'layers'
    color: 'purple'
